#!/usr/bin/bash

echo "---------------------------------------------"
echo " FOTA under linux not supported for now !!!!"
echo "---------------------------------------------"

echo $1
echo $2
echo $3
